#' Generate an EMPI-compatible Gabor dictionary
#'
#' Generates an XML dictionary file containing a set of Gabor atoms.
#'
#' The generated dictionary contains multiple Gabor blocks with logarithmically
#' distributed window lengths. The smallest window length is fixed to 17 samples
#' and the maximum window length is determined by \code{max_window_length}.
#' It can be set to the largest odd integer not exceeding either \code{3*N}
#' or \code{N-1}. The \code{3*N} upper limit is chosen heuristically.
#'
#' The window lengths are generated on a logarithmic scale and then quantized
#' to obtain a set of practical window sizes. Window lengths are forced to be
#' odd, which provides an exact temporal centre for symmetric Gaussian/Gabor
#' windows. The window shift is estimated as approximately 6 percent of the
#' window length:
#'
#' \deqn{windowShift = round(0.06 * windowLen)}
#'
#' The FFT size is selected as the smallest power of two satisfying:
#'
#' \deqn{fftSize >= 2 * windowLen}
#'
#' This corresponds to the zero-padding strategy commonly used in MPTK-like
#' Gabor dictionaries.
#'
#' @param N Integer. Length of the analyzed signal in samples.
#'
#' @param file Character string. Path to the XML file that will be created.
#'   The output follows the MPTK dictionary XML structure and contains Gabor
#'   blocks.
#'
#' @param max_window_length Character string specifying the upper limit used
#'   when generating window lengths. \code{"3N"} uses the largest odd integer not
#'   exceeding \code{3*N}, whereas \code{"N-1"} limits the largest window
#'   length to the largest odd integer not exceeding \code{N-1}.
#'   The default is \code{"3N"}.
#'
#' @return
#' The function writes an XML dictionary file to \code{file}. Invisibly returns a
#' data frame containing the generated dictionary parameters:
#'
#' \itemize{
#'   \item \code{windowLen} - Gabor window length in samples,
#'   \item \code{windowShift} - temporal shift between consecutive atoms,
#'   \item \code{fftSize} - FFT size used for the block.
#' }
#'
#' @details
#' The dictionary generation procedure is based on the following rules.
#' The rules were derived from an analysis of XML files generated by the
#' EMPI program using the \code{--dictionary-output} option (see the
#' \code{read_gabor_dict()} function and the corresponding vignette available
#' on CRAN).
#'
#' \enumerate{
#'   \item Minimum window length: 17 samples.
#'   \item Maximum window length: determined by \code{max_window_length}.
#'   \item Number of scales:
#'   \deqn{K = ceil(log2(N)) + 3}
#'   \item Logarithmic spacing of scales:
#'   \deqn{L_k = 17 r^k}
#'   where
#'   \deqn{r=(L_{max}/17)^{1/(K-1)}}
#'   \item Quantization of window lengths depending on their size.
#'   \item Enforcement of odd window lengths.
#'   \item Window shift proportional to window length.
#'   \item FFT size selected as a power of two.
#' }
#'
#' @export
#'
#' @seealso
#' \code{\link{read_gabor_dict}}
#'
#' @examples
#' # Generate a dictionary for a 256-sample signal
#' xml_file <- tempfile(fileext = ".xml")
#'
#' # Default setting: maximum window length based on 3*N
#' dict <- generate_xml_dict(
#'   N = 256,
#'   file = xml_file
#' )
#'
#' dict
#'
#' # Read the generated Gabor dictionary for a 2-second,
#' # 128-Hz signal (256 samples)
#' atoms_dict <- read_gabor_dict(
#'   xml_file,
#'   sampling_frequency = 128,
#'   duration = 2,
#'   full_atoms_in_signal = FALSE,
#'   verbose = TRUE
#' )
#'
#' head(atoms_dict)
#' tail(atoms_dict)
#'
#' # Alternative setting: limit the maximum window length to N-1
#' dict <- generate_xml_dict(
#'   N = 256,
#'   file = xml_file,
#'   max_window_length = "N-1"
#' )
#'
#' dict
#'
generate_xml_dict <- function(N, file, max_window_length = c("3N", "N-1")) {

  if (!is.numeric(N) ||
      length(N) != 1L ||
      !is.finite(N) ||
      N != as.integer(N) ||
      N < 18L) {
    stop("'N' must be an integer greater than or equal to 18.")
  }

  if (!is.character(file) ||
      length(file) != 1L ||
      is.na(file) ||
      !nzchar(file)) {
    stop("'file' must be a non-empty character string.")
  }

  max_window_length <- match.arg(max_window_length)

  N <- as.integer(N)

  Lmin <- 17

  if (max_window_length == "N-1") {
    Lmax <- N - 1
  } else {
    Lmax <- 3 * N
  }

  # Gabor windows are constrained to odd lengths.
  if (Lmax %% 2L == 0L) {
    Lmax <- Lmax - 1L
  }

  # Number of scales
  K <- ceiling(log2(N)) + 3

  # Logarithmic scale factor
  r <- (Lmax / Lmin)^(1 / (K - 1))
  rawLen <- Lmin * r^(0:(K-1))

  # Window length quantization
  # (rounding to a specific step)
    quantize_window <- function(x) {
    if(x < 64) {
      step <- 1
    } else if(x < 256) {
      step <- 2
    } else if(x < 1024) {
      step <- 4
    } else if(x < 4096) {
      step <- 8
    } else {
      step <- 16
    }

    y <- round(x / step) * step

    # The Gaussian/Gabor window is centered around the
    # center sample, so an odd length gives an exact center.
    if(y %% 2 == 0) y <- y + 1
    return(as.integer(y))
  }

  windowLen <- sapply(rawLen, quantize_window)
  windowLen[1] <- Lmin
  windowLen[length(windowLen)] <- Lmax

  # Removing repetitions
  windowLen <- unique(windowLen)

  # Monotonicity
  windowLen <- cummax(windowLen)

  # Window shift
  windowShift <- round(windowLen * 0.06)
  windowShift[windowShift < 1] <- 1

  # FFT size
  fftSize <- sapply(
    windowLen,
    function(L) {
      as.integer(2^ceiling(log2(2*L)))
    }
  )

  # XML
  con <- base::file(file, open="w")
  on.exit(close(con), add = TRUE)

  writeLines('<?xml version="1.0" encoding="ISO-8859-1"?>', con)
  writeLines('<dict>', con)

  for(i in seq_along(windowLen)) {
    block <- c('<block>', '<param name="type" value="gabor"/>',
      sprintf('<param name="windowLen" value="%d"/>', windowLen[i]),
      sprintf('<param name="windowShift" value="%d"/>', windowShift[i]),
      sprintf('<param name="fftSize" value="%d"/>', fftSize[i]),
      '</block>'
    )
    writeLines(block, con)
  }

  writeLines('</dict>', con)

  invisible(
    data.frame(
      windowLen = windowLen,
      windowShift = windowShift,
      fftSize = fftSize
    )
  )
}

