#' Generate an MPTK-like Gabor dictionary XML file
#'
#' Generates an XML dictionary file containing a set of Gabor atoms following
#' a reconstruction of the Matching Pursuit Tool Kit (MPTK) dictionary
#' generation strategy.
#'
#' The generated dictionary contains multiple Gabor blocks with logarithmically
#' distributed window lengths. The smallest window length is fixed to 17
#' samples and the largest window length is set to \code{N-1}, allowing atoms
#' longer than the analyzed signal through zero-padding during decomposition.
#'
#' The window lengths are generated on a logarithmic scale and then quantized
#' to obtain a set of practical window sizes. Window lengths are forced to be
#' odd, which provides an exact temporal centre for symmetric Gaussian/Gabor
#' windows. The window shift is estimated as approximately 6 percent of the
#' window length:
#'
#' \deqn{windowShift = round(0.06 * windowLen)}
#'
#' The FFT size is selected as the smallest power of two satisfying:
#'
#' \deqn{fftSize >= 2 * windowLen}
#'
#' This corresponds to the zero-padding strategy commonly used in MPTK-like
#' Gabor dictionaries.
#'
#' @param N Integer. Length of the analyzed signal in samples. The maximum
#'   generated window length is \code{N-1}.
#'
#' @param file Character string. Path to the XML file that will be created.
#'   The output follows the MPTK dictionary XML structure and contains Gabor
#'   blocks.
#'
#' @return
#' The function writes an XML dictionary file to \code{file}. Invisibly returns a
#' data frame containing the generated dictionary parameters:
#'
#' \itemize{
#'   \item \code{windowLen} - Gabor window length in samples,
#'   \item \code{windowShift} - temporal shift between consecutive atoms,
#'   \item \code{fftSize} - FFT size used for the block.
#' }
#'
#' @details
#' The dictionary generation procedure is based on the following rules.
#' The rules were derived from an analysis of XML files generated by the
#' EMPI program using the \code{--dictionary-output} option (see the
#' \code{read_dict()} function and the corresponding vignette available on CRAN).
#'
#' \enumerate{
#'   \item Minimum window length: 17 samples.
#'   \item Maximum window length: \code{N-1} samples.
#'   \item Number of scales:
#'   \deqn{K = ceil(log2(N)) + 3}
#'   \item Logarithmic spacing of scales:
#'   \deqn{L_k = 17 r^k}
#'   where
#'   \deqn{r=((N-1)/17)^{1/(K-1)}}
#'   \item Quantization of window lengths depending on their size.
#'   \item Enforcement of odd window lengths.
#'   \item Window shift proportional to window length.
#'   \item FFT size selected as a power of two.
#' }
#'
#' @export
#'
#' @seealso
#' \code{\link{read_dict}},
#'
#' @examples
#' \dontrun{
#' # Generate a dictionary for a 4096-sample signal
#' generate_xml_dict(
#'   N = 4096,
#'   file = "dictionary_4096.xml"
#' )
#'
#' # Inspect generated parameters without reading the XML file
#' xml_file <- tempfile(fileext = ".xml")
#'
#' dict <- generate_xml_dict(
#'   N = 256,
#'   file = xml_file
#' )
#'
#' dict
#'
#' atoms_dict <- read_dict(
#'   xml_file,
#'   sf = 128,
#'   duration = 2,
#'   verbose = TRUE
#' )
#'
#' head(atoms_dict)
#' tail(atoms_dict)
#' }
#'
generate_xml_dict <- function(N, file) {
  Lmin <- 17
  Lmax <- N - 1

  if(N < Lmin) stop("Signal length must be >= 17")

  # Number of scales
  K <- ceiling(log2(N)) + 3

  # Logarithmic scale factor
  r <- (Lmax / Lmin)^(1 / (K - 1))
  rawLen <- Lmin * r^(0:(K-1))

  # Window length quantization
  # (rounding to a specific step)
    quantize_window <- function(x) {
    if(x < 64) {
      step <- 1
    } else if(x < 256) {
      step <- 2
    } else if(x < 1024) {
      step <- 4
    } else if(x < 4096) {
      step <- 8
    } else {
      step <- 16
    }

    y <- round(x / step) * step

    # The Gaussian/Gabor window is centered around the
    # center sample, so an odd length gives an exact center.
    if(y %% 2 == 0) y <- y + 1
    return(as.integer(y))
  }

  windowLen <- sapply(rawLen, quantize_window)
  windowLen[1] <- Lmin
  windowLen[length(windowLen)] <- Lmax

  # Removing repetitions
  windowLen <- unique(windowLen)

  # Monotonicity
  windowLen <- cummax(windowLen)

  # Window shift
  windowShift <- round(windowLen * 0.06)
  windowShift[windowShift < 1] <- 1

  # FFT size
  fftSize <- sapply(
    windowLen,
    function(L) {
      as.integer(2^ceiling(log2(2*L)))
    }
  )

  # XML
  con <- file(file, open="w")

  writeLines('<?xml version="1.0" encoding="ISO-8859-1"?>', con)
  writeLines('<dict>', con)

  for(i in seq_along(windowLen)) {
    block <- c('<block>', '<param name="type" value="gabor"/>',
      sprintf('<param name="windowLen" value="%d"/>', windowLen[i]),
      sprintf('<param name="windowShift" value="%d"/>', windowShift[i]),
      sprintf('<param name="fftSize" value="%d"/>', fftSize[i]),
      '</block>'
    )
    writeLines(block, con)
  }

  writeLines('</dict>', con)
  close(con)

  invisible(
    data.frame(
      windowLen = windowLen,
      windowShift = windowShift,
      fftSize = fftSize
    )
  )
}

