#' Matching Pursuit (MP) or Orthogonal Matching Pursuit (OMP) decomposition
#' for multi-channel signals
#'
#' Performs sparse signal decomposition using either the Matching Pursuit (MP) or
#' Orthogonal Matching Pursuit (OMP) algorithm, as specified by the \code{mode}
#' parameter. The decomposition is performed independently for each signal channel
#' using a dictionary of candidate atoms generated by \code{topk_atoms()}.
#'
#' The returned object is of class \code{"mp"} and can be visualized using
#' \code{plot()} and \code{tf_map()}.
#'
#' @param mode
#' \code{"omp"} or \code{"mp"}. Specifies the algorithm to use for signal decomposition.
#'
#' @param dictionary A \code{"topk"} object returned by
#' \code{topk_atoms()}. It contains the candidate atoms and their associated
#' time-frequency parameters.
#'
#' @param signal A matrix, data frame, or object coercible to a matrix
#' containing the signal(s) to decompose. Signals are assumed to be stored in
#' columns.
#'
#' @param sf Sampling frequency of the signal in Hertz.
#'
#' @param n_nonzero_coefs Maximum number of atoms selected during the decomposition
#' for each signal channel.
#'
#' @param tol Optional stopping tolerance defined as the maximum allowed
#' relative residual energy. If specified, it overrides \code{n_nonzero_coefs}.
#'
#' @param normalize Logical; if \code{TRUE}, atoms are normalized to unit
#' \eqn{\ell_2} norm before decomposition.
#'
#' @param fit_intercept Logical; if \code{TRUE}, an intercept term is estimated
#' by centering both the signal and the dictionary atoms before
#' decomposition.
#' Only used when \code{mode == "omp"}.
#'
#' @param verbose Logical; if \code{TRUE}, progress information is printed
#' during processing.
#'
#' @return An object of class \code{"mp"} containing:
#'
#' \item{atoms}{A data frame describing the selected atoms.}
#' \item{original_signal}{Matrix containing the original signal(s).}
#' \item{reconstruction}{Matrix containing the reconstructed signal(s).}
#' \item{gabors}{List of matrices containing selected atoms for each channel.}
#' \item{t}{Time vector corresponding to signal samples.}
#' \item{sf}{Sampling frequency.}
#'
#' The \code{atoms} data frame contains:
#'
#' \itemize{
#' \item \code{channel_id} — signal channel identifier,
#' \item \code{atom_number} — atom index within the channel,
#' \item \code{energy} — atom energy contribution,
#' \item \code{envelope} — envelope type,
#' \item \code{frequency} — atom frequency (Hz),
#' \item \code{phase} — atom phase (radians),
#' \item \code{scale} — atom scale (seconds),
#' \item \code{position} — atom centre position (seconds).
#' }
#'
#' @details
#' The function applies \code{omp_core()} or \code{mp_core()} independently
#' to each signal channel. For every channel, the selected algorithm (MP or OMP)
#' greedily builds a sparse approximation of the signal using atoms from the
#' supplied "topk" dictionary.
#'
#' The resulting object follows the same structure as Matching Pursuit outputs,
#' enabling direct generation of time-frequency maps and visualizations
#' using `tf_map()` or `plot()` functions.
#'
#' Typical workflow:
#'
#' \enumerate{
#' \item Read a dictionary using \code{read_dict()}.
#' \item Generate a signal-adaptive subset of atoms using \code{topk_atoms()}.
#' \item Perform sparse decomposition using \code{mp_omp_execute()}.
#' \item Visualize the result using \code{plot()} or \code{tf_map()}.
#' }
#'
#' @seealso
#' \code{\link{read_dict}},
#' \code{\link{topk_atoms}},
#' \code{\link{omp_core}},
#' \code{\link{mp_core}},
#' \code{\link{mp_omp_run_pipeline}}
#'
#' @export
#'
#' @examples
#'
#' # +-------------------------------------------------------------+
#' # | Step 1: Read signal                                         |
#' # +-------------------------------------------------------------+
#' sig_file <- system.file(
#'   "extdata",
#'   "sample3.csv",
#'   package = "MatchingPursuit"
#' )
#'
#' sample <- read_csv_signals(
#'   sig_file,
#'   col_names_in_csv = TRUE
#' )
#'
#' sf <- sample$sampling_frequency
#' signal <- sample$signal
#' duration <- nrow(signal) / sf
#'
#' # +-------------------------------------------------------------+
#' # | Step 2: Read dictionary definition                          |
#' # +-------------------------------------------------------------+
#' xml_file <- system.file(
#'   "extdata",
#'   "sample3_dict.xml",
#'    package = "MatchingPursuit"
#' )
#'
#' atoms_dict <- read_dict(
#'   xml_file = xml_file,
#'   sf = sf,
#'   duration = duration,
#'   verbose = TRUE
#' )
#'
#' # +-------------------------------------------------------------+
#' # | Step 3: Generate signal-adaptive atom dictionary            |
#' # +-------------------------------------------------------------+
#' topk_dict <- topk_atoms(
#'   atoms_dict = atoms_dict,
#'   signal = signal,
#'   sf = sf,
#'   topk = 5000,
#'   verbose = TRUE
#' )
#'
#' # +-------------------------------------------------------------+
#' # | Step 4.1: Run Orthogonal Matching Pursuit                   |
#' # +-------------------------------------------------------------+
#' fit_omp <- mp_omp_execute(
#'   mode = "omp",
#'   dictionary = topk_dict,
#'   signal = signal,
#'   sf = sf,
#'   n_nonzero_coefs = 20,
#'   verbose = TRUE,
#'   fit_intercept = FALSE,
#' )
#'
#' # Inspect results
#' class(fit_omp)
#' head(fit_omp$atoms)
#'
#' # +-------------------------------------------------------------+
#' # | Step 4.2: Run Matching Pursuit                              |
#' # +-------------------------------------------------------------+
#' fit_mp <- mp_omp_execute(
#'   mode = "mp",
#'   dictionary = topk_dict,
#'   signal = signal,
#'   sf = sf,
#'   n_nonzero_coefs = 20,
#'   verbose = TRUE
#' )
#'
#' # Inspect results
#' class(fit_mp)
#' head(fit_mp$atoms)
#'
#' # +-------------------------------------------------------------+
#' # | Step 5: Time-frequency map                                  |
#' # +-------------------------------------------------------------+
#' plot(fit_omp, channel = 3)
#' plot(fit_mp, channel = 3)
#'
#' # +-------------------------------------------------------------+
#' # | Execute the complete pipeline (steps 1-4)                   |
#' # | using a single function                                     |
#' # +-------------------------------------------------------------+
#' fit <- mp_omp_run_pipeline(
#'   mode = "mp",         # or "omp" for Orthogonal Matching Pursuit
#'   sig_file = sig_file,
#'   col_names_in_csv = TRUE,
#'   xml_file = xml_file,
#'   topk = 5000,
#'   n_nonzero_coefs = 20,
#'   verbose = FALSE
#' )
#'
#' plot(fit, channel = 3)
#'
mp_omp_execute <- function (
    mode = NULL,
    dictionary,
    signal,
    sf,
    n_nonzero_coefs = NULL,
    tol = NULL,
    normalize = TRUE,
    fit_intercept = TRUE,
    verbose = FALSE
) {

  if (is.null(mode)) {
    stop("'mode' must be specified.")
  }

  if (!mode %in% c("mp", "omp")) {
    stop("'mode' must be either 'mp' or 'omp'.")
  }

  if (mode == "mp" && fit_intercept) {
    warning("'fit_intercept' is ignored when mode = 'mp'.")
  }
sss
  if (!is.matrix(signal)) {
    if (is.vector(signal) || is.data.frame(signal)) {
      signal <- as.matrix(signal)
    } else {
      stop("Parameter 'signal' must be a matrix or convertible to a matrix.")
    }
  }

  if (mode == "omp") {
    # run omp_core() for all channels
    results <- lapply(
      seq(1, ncol(signal)),
      function(ch) {
        res <- omp_core(
          dictionary = dictionary,
          signal = signal,
          channel = ch,
          tol = tol,
          n_nonzero_coefs = n_nonzero_coefs,
          normalize = normalize,
          fit_intercept = fit_intercept,
          verbose = verbose
        )
        if (verbose) message("mp_omp_execute(): channel ", ch, " processed.")
        res
      }
    ) }

  if (mode == "mp") {
    # run mp_core() for all channels
    results <- lapply(
      seq(1, ncol(signal)),
      function(ch) {
        res <- mp_core(
          dictionary = dictionary,
          signal = signal,
          channel = ch,
          tol = tol,
          n_nonzero_coefs = n_nonzero_coefs,
          normalize = normalize,
          verbose = verbose
        )
        if (verbose) message("mp_omp_execute(): channel ", ch, " processed.")
        res
      }
    ) }

  # Create 'mp' class object, compatible with tf_map() and plot.mp()
  channel_id <- c()
  atom_number <- c()
  energy <- c()
  envelope <- c()
  frequency <- c()
  phase <- c()
  scale <- c()
  position <- c()
  gabors <-list()

  n_channels <- length(results)
  n_samples <- nrow(results[[1]]$gabors)
  t <- seq(0, (n_samples - 1) / sf, by = 1 / sf)

  original_signal <- matrix(NA, nrow = n_samples, ncol = n_channels)
  reconstruction <- matrix(NA, nrow = n_samples, ncol = n_channels)

  for (r in 1:n_channels) {

    num_atoms <- ncol(results[[r]]$gabors)
    gabors[[r]] <- results[[r]]$gabors
    reconstruction[, r] <- results[[r]]$gabors %*% results[[r]]$coefs
    original_signal[, r] <- results[[r]]$original_signal

    i1 <- rep(r, num_atoms)
    channel_id <- c(channel_id, i1)

    i2 <- seq(1, num_atoms)
    atom_number <- c(atom_number, i2)

    i3 <- results[[r]]$energy
    energy <- c(energy, i3)

    i4 <- rep("gauss", num_atoms)
    envelope <-c(envelope, i4)

    i5 <- results[[r]]$frequency
    frequency <-c(frequency, i5)

    i6 <- results[[r]]$phase
    phase <-c(phase, i6)

    i7 <- results[[r]]$scale
    scale <-c(scale, i7)

    i8 <- results[[r]]$position
    position <-c(position, i8)
  }

  result <- list()
  result$atoms <- data.frame(
    channel_id,
    atom_number,
    energy,
    envelope,
    frequency,
    phase,
    scale,
    position
  )
  result$original_signal <- original_signal
  result$reconstruction <- reconstruction
  result$gabors <- gabors
  result$t <- t
  result$sf <- sf
  class(result) <- "mp"


  return(result)
}
