#' Convert multichannel signals to binary format
#'
#' @description
#' Converts a numeric matrix or data frame containing one or more signals
#' to the binary format required by EMPI. Rows correspond to samples and
#' columns to channels. Values are stored as 4-byte floating-point numbers
#' using little-endian byte order.
#'
#' For multichannel signals, samples are written in time order, with all channel values
#' for a given time point stored consecutively: first all channels at \code{t = 0},
#' then all channels at \code{t = }\eqn{\Delta t}, and so on.
#'
#' @param data Data frame containing the input signal(s).
#'
#' @param write_to_file If \code{TRUE}, a \code{.bin} file is created and saved in the
#' \code{path} directory or, if \code{path = NULL}, in the cache directory.
#'
#' @param path Directory in which the binary file will be saved.
#' If \code{NULL}, the file will be saved in the cache directory.
#'
#' @param file_name Name of the file to create if \code{write_to_file = TRUE}.
#'
#' @return A \code{raw} vector containing the binary representation of the signal.
#' If \code{write_to_file = TRUE}, a \code{.bin} file is additionally created.
#'
#' @note The \code{.bin} files generated by this function are not intended for direct
#' user manipulation. They are used internally by \code{empi_execute()}. The external
#' program \emph{Enhanced Matching Pursuit Implementation} (EMPI) requires binary input
#' data. This conversion utility may also be useful for users who wish to run EMPI
#' outside of the R environment.
#'
#' @export
#'
#' @examples
#' file <- system.file("extdata", "sample3.csv", package = "MatchingPursuit")
#' out <- read_csv_signals(file, col_names_in_csv = TRUE)
#'
#' signal_bin <- signal_to_bin(data = out$signal, write_to_file = FALSE)
#'
#' # We have 3 channels. The first 4 time points.
#' head(out$signal, 4)
#'
#' # The same elements of the signal in binary (floats are stored in 4 bytes).
#' head(signal_bin, 48)
#'
#' # After decoding to numeric.
#' # Of course we get the same values as in out$signal.
#' readBin(signal_bin[1:4], what = "numeric", size = 4, endian = "little")
#' readBin(signal_bin[5:8], what = "numeric", size = 4, endian = "little")
#' readBin(signal_bin[41:44], what = "numeric", size = 4, endian = "little")
#' readBin(signal_bin[45:48], what = "numeric", size = 4, endian = "little")
#'
signal_to_bin <- function(data, write_to_file = FALSE, path = NULL, file_name = NULL) {

  if (!is.data.frame(data) && !is.matrix(data)) {
    stop("'data' must be a data frame or matrix.")
  }

  if (!all(vapply(data, is.numeric, logical(1)))) {
    stop("'data' must contain numeric values only.")
  }

  signal_raw <- raw()
  for (m in 1:nrow(data)) {
    data_row <- as.numeric(data[m, ])
    signal_raw <- c(signal_raw, writeBin(data_row, raw(), size = 4, endian = "little"))
  }

  if (write_to_file) {

    if (is.null(path)) {
      dest_dir <- tools::R_user_dir("MatchingPursuit", "cache")
      dir.create(dest_dir, recursive = TRUE, showWarnings = FALSE)
    } else {
      dest_dir <- path
      if (!dir.exists(dest_dir)) {
        ok <- dir.create(dest_dir, recursive = TRUE, showWarnings = FALSE)
        if (!ok && !dir.exists(path)) {
          stop("Cannot create directory '", dest_dir, "'.")
        }
      }
    }

    if (is.null(file_name)) {
      temp <- file.path(dest_dir, "signal.bin")
      writeBin(signal_raw, temp)
      message("Binary file saved to '", temp, "'.")
    } else {
      temp <- file.path(dest_dir, file_name)
      writeBin(signal_raw, temp)
      message("Binary file saved to '", temp, "'.")
    }
  }


  return(signal_raw)
}

